name: test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --sanitize=thread
  macOS:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --sanitize=thread
